### PR TITLE
Update position camera handler

### PR DESCRIPTION
**Pull request by ddelpiano**

### CODE REVIEW

**Comment by ddelpiano** [comment]
> @ddelpiano shouldn't we also propagate back to Canvas? https://github.com/MetaCell/geppetto-meta/blob/master/geppetto.js/geppetto-ui/src/3d-canvas/Canvas.js#L195

Hey Nico, that is only the defaultProps, the cameraHandler is already linked to the ThreeDEngine instance we create at [here](https://github.com/MetaCell/geppetto-meta/blob/9432ac42018391d32c603902032948c8f6d87353/geppetto.js/geppetto-ui/src/3d-canvas/Canvas.js#L43). 
Feel free to have a second look tomorrow and then merge this. Thx

**Review by afonsobspinto — CHANGES_REQUESTED** [review]
Doesn't fix #176 for me, in Yal

https://user-images.githubusercontent.com/19196034/139831065-3de81e64-7882-4ffc-b031-c654fd3fb263.mp4

e.

**Comment by afonsobspinto** [comment]
#176 is fixed by #193 for me. Can we close this PR @ddelpiano ?

**Comment by enicolasgomez** [comment]
@ddelpiano final word on you.

**Pull request closed without merging**
