### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by ddelpiano**
- Layout manager minor fixes to sync the state of the widget config on layout actions
- Canvas improvements and working on hierarchy
- Canvas code optimisation
- Canvas resizing fixed
- 3d element selection offsetted in netpyne fixed
- 3d elements visibility logic implemented

### CODE REVIEW

**Comment by ddelpiano** [comment]
@enicolasgomez @afonsobspinto fyi I tried to test this branch with the showcase but the latest does not compile locally due to the below

```
ERROR in ./node_modules/@ampproject/remapping/dist/remapping.mjs 186:47-55
Can't import the named export 'TraceMap' from non EcmaScript module (only default export is available)
 @ ./node_modules/@babel/core/lib/transformation/file/merge-map.js
 @ ./node_modules/@babel/core/lib/transformation/file/generate.js
 @ ./node_modules/@babel/core/lib/transformation/index.js
 @ ./node_modules/@babel/core/lib/transform.js
 @ ./node_modules/@babel/core/lib/index.js
 @ ./node_modules/react-docgen/dist/babelParser.js
 @ ./node_modules/react-docgen/dist/parse.js
 @ ./node_modules/react-docgen/dist/main.js
 @ ./src/components/showcase/ShowcaseUtils.js
 @ ./src/components/showcase/Showcase.jsx
 @ ./src/pages/programmatic/pythonconsole.js
 @ ./src/pages/index.js
 @ ./src/components/Main.jsx
 @ ./src/App.js
 @ ./src/index.js

ERROR in ./node_modules/@ampproject/remapping/dist/remapping.mjs 228:25-33
Can't import the named export 'TraceMap' from non EcmaScript module (only default export is available)
 @ ./node_modules/@babel/core/lib/transformation/file/merge-map.js
 @ ./node_modules/@babel/core/lib/transformation/file/generate.js
 @ ./node_modules/@babel/core/lib/transformation/index.js
 @ ./node_modules/@babel/core/lib/transform.js
 @ ./node_modules/@babel/core/lib/index.js
 @ ./node_modules/react-docgen/dist/babelParser.js
 @ ./node_modules/react-docgen/dist/parse.js
 @ ./node_modules/react-docgen/dist/main.js
 @ ./src/components/showcase/ShowcaseUtils.js
 @ ./src/components/showcase/Showcase.jsx
 @ ./src/pages/programmatic/pythonconsole.js
 @ ./src/pages/index.js
 @ ./src/components/Main.jsx
 @ ./src/App.js
 @ ./src/index.js

ERROR in ./node_modules/@ampproject/remapping/dist/remapping.mjs 96:29-44
Can't import the named export 'decodedMappings' from non EcmaScript module (only default export is available)
 @ ./node_modules/@babel/core/lib/transformation/file/merge-map.js
 @ ./node_modules/@babel/core/lib/transformation/file/generate.js
 @ ./node_modules/@babel/core/lib/transformation/index.js
 @ ./node_modules/@babel/core/lib/transform.js
 @ ./node_modules/@babel/core/lib/index.js
 @ ./node_modules/react-docgen/dist/babelParser.js
 @ ./node_modules/react-docgen/dist/parse.js
 @ ./node_modules/react-docgen/dist/main.js
 @ ./src/components/showcase/ShowcaseUtils.js
 @ ./src/components/showcase/Showcase.jsx
 @ ./src/pages/programmatic/pythonconsole.js
 @ ./src/pages/index.js
 @ ./src/components/Main.jsx
 @ ./src/App.js
 @ ./src/index.js

ERROR in ./node_modules/@ampproject/remapping/dist/remapping.mjs 241:50-65
Can't import the named export 'decodedMappings' from non EcmaScript module (only default export is available)
 @ ./node_modules/@babel/core/lib/transformation/file/merge-map.js
 @ ./node_modules/@babel/core/lib/transformation/file/generate.js
 @ ./node_modules/@babel/core/lib/transformation/index.js
 @ ./node_modules/@babel/core/lib/transform.js
 @ ./node_modules/@babel/core/lib/index.js
 @ ./node_modules/react-docgen/dist/babelParser.js
 @ ./node_modules/react-docgen/dist/parse.js
 @ ./node_modules/react-docgen/dist/main.js
 @ ./src/components/showcase/ShowcaseUtils.js
 @ ./src/components/showcase/Showcase.jsx
 @ ./src/pages/programmatic/pythonconsole.js
 @ ./src/pages/index.js
 @ ./src/components/Main.jsx
 @ ./src/App.js
 @ ./src/index.js

ERROR in ./node_modules/@ampproject/remapping/dist/remapping.mjs 241:73-88
Can't import the named export 'encodedMappings' from non EcmaScript module (only default export is available)
 @ ./node_modules/@babel/core/lib/transformation/file/merge-map.js
 @ ./node_modules/@babel/core/lib/transformation/file/generate.js
 @ ./node_modules/@babel/core/lib/transformation/index.js
 @ ./node_modules/@babel/core/lib/transform.js
 @ ./node_modules/@babel/core/lib/index.js
 @ ./node_modules/react-docgen/dist/babelParser.js
 @ ./node_modules/react-docgen/dist/parse.js
 @ ./node_modules/react-docgen/dist/main.js
 @ ./src/components/showcase/ShowcaseUtils.js
 @ ./src/components/showcase/Showcase.jsx
 @ ./src/pages/programmatic/pythonconsole.js
 @ ./src/pages/index.js
 @ ./src/components/Main.jsx
 @ ./src/App.js
 @ ./src/index.js

ERROR in ./node_modules/@ampproject/remapping/dist/remapping.mjs 158:15-34
Can't import the named export 'presortedDecodedMap' from non EcmaScript module (only default export is available)
 @ ./node_modules/@babel/core/lib/transformation/file/merge-map.js
 @ ./node_modules/@babel/core/lib/transformation/file/generate.js
 @ ./node_modules/@babel/core/lib/transformation/index.js
 @ ./node_modules/@babel/core/lib/transform.js
 @ ./node_modules/@babel/core/lib/index.js
 @ ./node_modules/react-docgen/dist/babelParser.js
 @ ./node_modules/react-docgen/dist/parse.js
 @ ./node_modules/react-docgen/dist/main.js
 @ ./src/components/showcase/ShowcaseUtils.js
 @ ./src/components/showcase/Showcase.jsx
 @ ./src/pages/programmatic/pythonconsole.js
 @ ./src/pages/index.js
 @ ./src/components/Main.jsx
 @ ./src/App.js
 @ ./src/index.js

ERROR in ./node_modules/@ampproject/remapping/dist/remapping.mjs 76:24-36
Can't import the named export 'traceSegment' from non EcmaScript module (only default export is available)
 @ ./node_modules/@babel/core/lib/transformation/file/merge-map.js
 @ ./node_modules/@babel/core/lib/transformation/file/generate.js
 @ ./node_modules/@babel/core/lib/transformation/index.js
 @ ./node_modules/@babel/core/lib/transform.js
 @ ./node_modules/@babel/core/lib/index.js
 @ ./node_modules/react-docgen/dist/babelParser.js
 @ ./node_modules/react-docgen/dist/parse.js
 @ ./node_modules/react-docgen/dist/main.js
 @ ./src/components/showcase/ShowcaseUtils.js
 @ ./src/components/showcase/Showcase.jsx
 @ ./src/pages/programmatic/pythonconsole.js
 @ ./src/pages/index.js
 @ ./src/components/Main.jsx
 @ ./src/App.js
 @ ./src/index.js
```

**Review by afonsobspinto — CHANGES_REQUESTED** [review]
I fixed the compilation error on geppetto-showcase (which was happening on development as well).
Then I tried to see the canvas examples and the instances were not showing up.
A couple of warnings show up in the console but doesn't seem related. I didn't investigate further
image

**Comment by ddelpiano** [comment]
@afonsobspinto @enicolasgomez I fixed the above mentioned by Afonso, please feel free to re-test this. Thx!

**Review by afonsobspinto — APPROVED** [review]
Everything seems ok in geppetto-showcase.
react-redux-example isn't working properly (not sure if it's caused by this PR or not) but it doesn't matter much because it is something to address on #256.
I locally tested feature #307 and it is working.
Couldn't test the other issues addressed in this PR but the code looks fine

**Pull request merged**
