### PR TITLE
Rebased from development and applied feature/122 changes. 

### PR DESCRIPTION
**Pull request by enicolasgomez**
Added setRotationalSpeed and resetRotationalSpeed to engine so they are controlled when ROTATE from cameraManager to avoid losing control on the animation frame.

### CODE REVIEW

**Comment by enicolasgomez** [comment]
Continued from https://github.com/MetaCell/geppetto-meta/pull/221

- added setRotationalSpeed and resetRotationalSpeed to engine
- using both interfaces from cameraManager

the rational behid this fix is that, when in the rotation loop, is better to give control to the engine that firing multiple rotation updates from the cameraManager, which is prone to sync issues with other request frames. This why we give the engine control on what. to render.

For doing that, a large rotational angle is prefered to be passed. The problem is that with the existing rotational speed value, it will rotate too fast making it un-usable.

That's why this two interfaces have been introduced, so when activate the rotation control:

- a large rotational angle is passed
- the rotational speed is reduced drastically
- the rotation event is fired in larger intervals

**Review by afonsobspinto — CHANGES_REQUESTED** [review]
It seems to me that the hovering is not working properly.
I didn't dig into what was the cause but here's a video showing me hovering one of the simpleInstances and the getIntersectedObjects code not detecting it:

https://user-images.githubusercontent.com/19196034/145996832-9f7615b3-e8ec-46a2-abe5-36c3a089f2ff.mp4

Selection doesn't seem to be working either

**Comment by enicolasgomez** [comment]
@afonsobspinto the hovering issue has been reported on other ticket:
https://app.zenhub.com/workspaces/geppetto-meta-6047b13d88e7e70013d4589b/issues/metacell/geppetto-meta/223

it's already happening on development branch.

This was about fixing the getIntersectedObjects performance as it was trasversing the objects each time it was called. About rotation, because of that and the way it rotation worked before the above described fix, it slowed down.

IMHO we could merge this one and then focus on 223

**Review by afonsobspinto — APPROVED** [review]

**Comment by afonsobspinto** [comment]
I didn't know about that. 
[This](https://app.zenhub.com/workspaces/geppetto-meta-6047b13d88e7e70013d4589b/issues/metacell/geppetto-meta/223) is also affecting selection which is one of the most basic features of the canvas.

Approving this one because indeed the issues I reported are already in development.

**Pull request merged**
