### PR TITLE
Feature/201 functional refactoring

### PR DESCRIPTION
**Pull request by Muhaddatha**
- Fixed errors regarding undefined functions by binding the setup renderer function to the ThreeDEngine class.
- Hovering over objects in the Yale canvas seems to be working. 

@zsinnema Is this how the hovering should act when there are multiple objects in the Canvas?

https://drive.google.com/file/d/1mpI7qbPzios4YUXLLbfJQCE-uX7EkM1O/view?usp=sharing

### CODE REVIEW

**Comment by zsinnema** [comment]
@Muhaddatha I have no idea if your fix fixes the issue with the event listeners in functional components.
I fixed the hovering issue in Yale last week by getting the current viewer Geppetto Instances from the redux store.

If you tested your fix on the latest Yale development branch then it could be that you are facing my fix. You can test your fix by replaceing line 125 by this: `const localInstances = instances;`

**Comment by enicolasgomez** [comment]
@Muhaddatha there's a known issue with hovering that has not been addressed yet, if you see something weird just in that event and everything else is working then it's probably it

**Comment by enicolasgomez** [comment]
@Muhaddatha seeing two things here:

1. CanvasExample is still a Class component
2. Geppetto-Showcase stopped working

**Comment by Muhaddatha** [comment]
- Conflicts solved and code is replaced on branch [feature/201_refactoring](https://github.com/MetaCell/geppetto-meta/pull/231)

**Pull request closed without merging**
