### PR TITLE
#135 Use react-resize-detector to resize Canvas

### PR DESCRIPTION
**Pull request by lrebscher**
* Remove resize event calls from flexLayout since it messes up Canvas resizing
* Don't use resize listener instead use react-resize-detector to resize Canvas
* Add cameraControls.css since .less is not supported by CRA (temporarily until #141 is decided )

### CODE REVIEW

**Comment by lrebscher** [comment]
@ddelpiano @filippomc  would be good to get your feedback on this approach.

In summary: flexLayout won't trigger resizing events anymore, instead we use the `react-resize-detector` package to listen to changes in width/height of parent div.

A "normal" div will automatically resize to flexLayout changes, there is no need to listen to resize events in that case. A canvas element can adapt with this package to the width/height of its parent div.

Further, the flexLayout resize trigger causes issues, observed that there are timeout issues where the resize event causes the Canvas to adapt a wrong height although its parent container has the correct one.


@ddelpiano this needs to be adopted to Graph.js once merged

**Comment by filippomc** [comment]
Yes that resize event was a ugly workaround. This new approach whould work better also when the resize comes from main browser window resizing.

Need to check other components that may be listening to the old event, probably graph, plot and connectivity.

**Comment by lrebscher** [comment]
I checked Graph but it's not used there anymore #138 , the only component that listens to resize event is the Search component and the [comments](https://github.com/MetaCell/geppetto-meta/blob/80edf731e0d7dcbc9366050fe5e94f36ba452197/geppetto.js/geppetto-ui/src/search/Search.tsx#L616) indicate that it's due to browser resizing.

**Review by filippomc — APPROVED** [review]
Looks good to me

**Pull request merged**
