### PR TITLE
Feature/305 refactor showcase examples

### PR DESCRIPTION
**Pull request by Muhaddatha**
- Moved all showcase examples out of geppetto-ui and into geppetto-showcase.
- Old example files are still left in geppetto-ui. Will remove them if this PR is approved because of a few minor bugs mentioned [here](https://app.zenhub.com/workspaces/geppetto-meta-6047b13d88e7e70013d4589b/issues/metacell/geppetto-meta/305).

### CODE REVIEW

**Comment by enicolasgomez** [comment]
@Muhaddatha looking good. Could you also remove the showcase files from UI before approving the PR? I would like to give a try to the whole thing so we don't test a false positive because components are imported from different locations and it will be difficult to follow. 

still confused about the two bugs you mentioned, those "are coloring for Canvas and node size in Graph components" ?

**Comment by Muhaddatha** [comment]
@enicolasgomez , you're right. It's not clear what the bug is without pictures. I attached them below:
Graph before:
image
Graph after:
image
Canvas VFB example before:
image
Canvas VFB example after:
image
Canvas simple instances before:
image
Canvas simple instances after:
image
Canvas multiple instances example before:
image
Canvas multiple instances example after:
image

**Comment by afonsobspinto** [comment]
@Muhaddatha I had a chance to have a look at this and everything seems all right to me. The "bugs" you mentioned are not bugs but rather some example configurations that changed. 

[This commit](https://github.com/MetaCell/geppetto-meta/commit/fabb44e330262b4a2cced92e27b2d146a3ab1b15) shows how to change the color of the instances in the canvas and the size of the nodes in the graph viewer.

I took the liberty to merge my #328 branch into yours and pushed that into https://github.com/MetaCell/geppetto-meta/tree/feature/305_latest (If I were you I would continue my work there, because it fixes a couple of issues + it will probably get into development soon) 

Two small things still missing are:
- Search showcase is still under geppetto-ui. Currently it's not active in the geppetto showcase app but is better have it in the right place.
- Flexlayout showcase is also under geppetto-ui. I will happily mention issue number #1 (it is not everyday you can mention the first issue in the repo) here as it might come in handy to know about it for this change (just speculating).

**Comment by Muhaddatha** [comment]
@afonsobspinto thanks for the detailed review. I will use the 305_latest branch.

- For the searchShowcase, I noticed that there is a [Search.js](https://github.com/MetaCell/geppetto-meta/blob/feature/305_latest/geppetto.js/geppetto-ui/src/search/showcase/Search.js) file in the showcase folder, but it doesn't seem like it's being used anywhere. At a closer look, I see that it is defining proptypes. Should the proptypes definitions go into the [Search.tsx](https://github.com/MetaCell/geppetto-meta/blob/feature/305_latest/geppetto.js/geppetto-ui/src/search/Search.tsx) component instead?
- You're right. I forgot to remove the flex-layout showcase folder from geppetto-ui. I'm a little confused about your second point. For issue #1, we want to get rid of the [FlexLayout.Layout file](https://github.com/MetaCell/geppetto-meta/blob/feature/305_latest/geppetto.js/geppetto-ui/src/flex-layout/showcase/FlexLayout.Layout.js#L13), right? Atm, I don't see a component/element dedicated to FlexLayout. So do the do contents of FlexLayout.Layout have to go in [FlexLayoutShowcase.js](https://github.com/MetaCell/geppetto-meta/blob/feature/305_latest/geppetto.js/geppetto-ui/src/flex-layout/showcase/examples/FlexLayoutShowcase.js)?

**Comment by afonsobspinto** [comment]
Good question! I forgot that the Search component is in the same situation as the FlexLayout component.
>Should the proptypes definitions go into the [Search.tsx](https://github.com/MetaCell/geppetto-meta/blob/feature/305_latest/geppetto.js/geppetto-ui/src/search/Search.tsx) component instead?

>https://github.com/MetaCell/geppetto-meta/issues/1, we want to get rid of the [FlexLayout.Layout file](https://github.com/MetaCell/geppetto-meta/blob/feature/305_latest/geppetto.js/geppetto-ui/src/flex-layout/showcase/FlexLayout.Layout.js#L13), right?

The answer is yes for both. That's the idea of #1. I foresaw that you would find those workaround files so that's why I mentioned it earlier but I don't think it matters for the current PR/issue, I just wanted you too know. 

>So do the do contents of FlexLayout.Layout have to go in [FlexLayoutShowcase.js](https://github.com/MetaCell/geppetto-meta/blob/feature/305_latest/geppetto.js/geppetto-ui/src/flex-layout/showcase/examples/FlexLayoutShowcase.js)?

No. Honestly it's not clear to me right now where the props should go. It cannot be in the FlexLayoutShowcase file because the props should refer to the FlexLayout component itself. At a first look, maybe reading them from https://github.com/MetaCell/geppetto-meta/blob/feature/305_latest/geppetto.js/geppetto-ui/src/flex-layout/src/view/Layout.tsx would be the approach. But we can see that whenever we decide to handle #1

**Pull request merged**
