### PR TITLE
#161 #162 Improvements on the layout management

### LINKED ISSUE #161: Layout tab title changes back to "initial" title after update widget
After an update widget the title of the tab is changed to the initial title

see video
[layout_title_change_after_widget_update.webm.zip](https://github.com/MetaCell/geppetto-meta/files/7183882/layout_title_change_after_widget_update.webm.zip)

### PR DESCRIPTION
**Pull request by filippomc**
Closes #161 #162

### CODE REVIEW

**Comment by filippomc** [comment]
> @filippomc when I use this release I get the following error:
> 
>      | ^  75 |   return true;
> ```

@zsinnema it looks like there is a problem with the THREE variable. Are you using yarn?

**Comment by zsinnema** [comment]
@filippomc yes, I'm using yarn

**Review by ddelpiano — APPROVED** [review]

**Comment by ddelpiano** [comment]
tested with the test application, lgtm.
@zsinnema for yale we need to extend the middleware to listed for the update widget action so that we can sync the widget names rendered across sidebar and flexlayout, the widget state now got the right information.

**Comment by zsinnema** [comment]
> tested with the test application, lgtm. @zsinnema for yale we need to extend the middleware to listed for the update widget action so that we can sync the widget names rendered across sidebar and flexlayout, the widget state now got the right information.

@ddelpiano thanks for testing it, about the widget: I'm already using the widget for getting all info (sidebar, ....)

**Comment by zsinnema** [comment]
@filippomc when I use `yarn link` to link the geppetto meta of this branch I get this:
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
▶ 27 stack frames were collapsed.
(anonymous function)
/opt/projects/metacell/yale/geppetto-NeuroSCAN/applications/neuroscan/frontend/geppetto-meta/geppetto.js/geppetto-client/build/common/layout/LayoutManager.js:269
  266 | }
  267 | 
  268 | if (nextAction) {
> 269 |   next(action);
      | ^  270 | }
  271 | 
  272 | if (nextSetLayout) {
View compiled
(anonymous function)
/opt/projects/metacell/yale/geppetto-NeuroSCAN/applications/neuroscan/frontend/geppetto-meta/geppetto.js/geppetto-client/build/common/middleware/geppettoMiddleware.js:44
  41 | }
  42 | 
  43 | if (!actionTriggered) {
> 44 |   next(action);
     | ^  45 | }
  46 | 
  47 | return;
View compiled
(anonymous function)
src/redux/searchMiddleware.js:24
  21 |     }
  22 | 
  23 |     default:
> 24 |       next(action);
  25 |   }
  26 | };
  27 | 
View compiled
(anonymous function)
src/redux/middleware.js:68
  65 |     }
  66 | 
  67 |     default:
> 68 |       next(action);
  69 |   }
  70 | };
  71 | 
View compiled
dispatch
node_modules/redux/es/redux.js:659
(anonymous function)
src/redux/middleware.js:51
  48 |     cameraOptions: defaultCameraOptions,
  49 |     viewerId: uuidv4(),
  50 |   };
> 51 |   store.dispatch(addWidget(widgetFromViewerSpec(newWidget)));
     | ^  52 | } else {
  53 |   const newWidget = {
  54 |     ...widget,
View compiled
```

**Pull request merged**
