### PR TITLE
Feature/68 npm package preparation

### PR DESCRIPTION
**Pull request by lrebscher**

### CODE REVIEW

**Review by afonsobspinto — APPROVED** [review]
The hot-reload with nodeman doesn't seem to work when we only change the Readme.md. That's not a problem since it's very atypical that we only need to change the markdown files. Aside from that everything worked fine in a fresh installation of geppetto-showcase

**Comment by afonsobspinto** [comment]
Meanwhile, I remembered that we probably should have a discussion about [this](https://github.com/openworm/geppetto-client/issues/349) in the context of this PR

**Comment by lrebscher** [comment]
Thanks for bringing it up, now tracked with #81 in geppetto-meta

**Review by filippomc — APPROVED** [review]
lgtm

**Pull request merged**
